knp_snappy:
    temporary_folder: "%kernel.cache_dir%/snappy"
    process_timeout: 20 # In seconds
    pdf:
        enabled:    true
        binary:     /usr/local/bin/wkhtmltopdf
        options:    []
    image:
        enabled:    true
        binary:     /usr/local/bin/wkhtmltoimage
        options:    []
